### ISSUE TITLE
Some datasets use less standard EVID values

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2data#1]
Looking at the theo_sd dataset, I see that the `EVID` column is set to `101` instead of the value of `1` that I expected.  Is it okay to change this to 1?  Alternatively, should I accept `101` as a dosing `EVID` for the PKNCA link?

**Comment by mattfidler** [comment]
If you run theo-sd through the normalizer discussed this morning the evids would be standardized

**Comment by mattfidler** [comment]
In general evids can take a much broader variety of values but all could be accepted
